name: Build Hugo files

on:
  push:
  pull_request:

env:
  HUGO_VERSION: 0.154.4

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.artifact.artifact-url }}


    steps:
      - uses: actions/checkout@v6

      - name: Install Hugo
        run: |
          wget --no-verbose -O hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
          sudo apt install ./hugo.deb
          rm hugo.deb

      - name: Build
        working-directory: hugo
        shell: bash
        run: |
          hugo version
          hugo --minify

      - uses: actions/upload-artifact@v6
        id: artifact
        with:
          name: 'mumble-www-files.zip'
          path: 'public'
          compression-level: 9
